name: LUDe
channels:
- rdkit
- conda-forge
- defaults
dependencies:
    - libgcc=5.2.0
    - pip
    - pip:
        - pandas==1.0.1
        - numpy==1.18.1
        - seaborn
        - xgboost==1.0.2
        - biopython
        - streamlit==1.2.0
        - streamlit_tags
        - git+https://github.com/gadsbyfly/PyBioMed
        - protobuf~=3.19.0
